export default interface Cabecero{
    Adicionales:boolean,
    Camaras:boolean,
    Cliente:string,
    DiasLaborables:string,
    DiasLaborablesPartida:boolean,
    Empresa:string,
    FactorAdministracion:boolean,
    FactorCoordinador:boolean,
    FactorEjecutivoCuenta:boolean,
    FactorSupervicion:boolean,
    Factores:boolean,
    FactorRegistro:boolean,
    Guardias:boolean,
    HorarioLaboral :string,
    ID :string,
    Nombre:string,
    NumeroUnidades:string,
    PeriodoServicio:string,
    Planta :string,
    PlantaNombre:string,
    Posturero:boolean,
    PostureroNumero:string,
    PostureroPartida:boolean,
    Presupuesto:string,
    DescImporte:string,
    DescPorcentaje:string,
    Turnos:string,
    TurnosPartida:boolean,
    UltimaModificacion:string,
    UnidadesGuardia:boolean,
    Usuario:string,
    Wifi:boolean,
    Aire:boolean,

  }
  